server:
  port: 5000
  read_timeout: 30s
  write_timeout: 30s

clickhouse:
  hosts:
    - localhost:8123
  database: default
  username: default
  password: Sw@123456
  dial_timeout: 10s

models:
  path: ./model
  watch: false
